version: '3'
services:
  backend:
    extends:
      file: ../Backend/docker-compose.yml
      service: backend
  database:
    extends:
      file: ../Backend/docker-compose.yml
      service: database
  frontend:
    image: medishare.frontend
    build:
      context: .
    environment:
      - CHOKIDAR_USEPOLLING=true # create-ui-app <= 5.x
      - WATCHPACK_POLLING=true # create-ui-app >= 5.x
      - FAST_REFRESH=false
    env_file:
        - .env
    command: npm start
    volumes:
      - ./src:/frontend/src
      - ./public:/frontend/public
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  db-backend:
    name: db-backend
