# Generated by Django 3.2.5 on 2022-05-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Article_title', models.CharField(max_length=100)),
                ('Article_summary', models.TextField()),
                ('Article_authors', models.CharField(default='', max_length=200)),
                ('Article_link', models.CharField(default='', max_length=75)),
            ],
        ),
    ]
