# Generated by Django 3.2.13 on 2022-05-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nsfw',
        ),
    ]
