# Generated by Django 3.2.3 on 2022-05-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='horoscope',
            field=models.CharField(default='Aquarius', max_length=12),
        ),
    ]
