# Generated by Django 3.2.3 on 2022-05-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_horoscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='horoscope',
            field=models.CharField(choices=[(1, 'aries'), (2, 'taurus'), (3, 'gemini'), (4, 'cancer'), (5, 'leo'), (6, 'virgo'), (7, 'libra'), (8, 'scorpio'), (9, 'sagittarius'), (10, 'capricorn'), (11, 'aquarius'), (12, 'pisces')], default='aries', max_length=11),
        ),
    ]
