# Generated by Django 3.2.3 on 2022-05-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_horoscope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='horoscope',
            field=models.CharField(choices=[('aries', 'Aries'), ('taurus', 'Taurus'), ('gemini', 'Gemini'), ('cancer', 'Cancer'), ('leo', 'Leo'), ('virgo', 'Virgo'), ('libra', 'Libra'), ('scorpio', 'Scorpio'), ('sagittarius', 'Sagittarius'), ('capricorn', 'Capricorn'), ('aquarius', 'Aquarius'), ('pisces', 'Pisces')], default='aries', max_length=11),
        ),
    ]
