# Generated by Django 3.2.5 on 2022-05-16 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_alter_user_mail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 5, 16, 8, 11, 10, 500692, tzinfo=utc), verbose_name='date published')),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('parentType', models.BooleanField(default=True)),
                ('parentID', models.IntegerField(default=0)),
                ('isMarkedNSFW', models.BooleanField(default=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
