version: '3'
services:
  database:
    build:
      context: ./docker_database
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - ./_temp_db:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: ./docker_backend/Dockerfile
    command: ../init_backend.sh
    volumes:
      - .:/backend/django
    expose:
      - 8000
    ports:
      - "8000:8000"
    env_file:
        - .env
    depends_on:
      - database